#!/bin/bash 
#Program Calculator 
 
 
   penambahan(){ 
 
   echo " M4SUKAN 4NGK4NY4 BOSS : " 
 
   read p 
 
   echo " M4SUK4N 4NGKA K3DU4 : " 
 
   read q 
 
   Tambah=$(echo "$p + $q" | bc) 
 
   echo "Dan Hasilnya Adalah = $Tambah" 
 
   sleep 5 
 
   } 
 
 
 
   pengurangan(){ 
 
   echo " M4SUKAN 4NGK4NY4 BOSS : " 
 
   read p 
 
   echo " M4SUK4N 4NGKA K3DU4 : " 
 
   read q 
 
   Kurang=$(echo "$p - $q" | bc) 
 
   echo "dan hasilnya Adalah = $Kurang" 
 
   sleep 5 
 
   } 
 
 
 
   perkalian(){ 
 
   echo " M4SUKAN 4NGK4NY4 BOSS : " 
 
   read p 
 
   echo " M4SUK4N 4NGKA K3DU4 : " 
 
   read q 
 
   Kali=$(echo "$p * $q" | bc) 
 
   echo "dan hasilnya Adalah = $Kali" 
 
   sleep 5 
 
   }     
 
   pembagian(){ 
 
   echo " M4SUKAN 4NGK4NY4 BOSS : " 
 
   read p 
 
   echo " M4SUK4N 4NGKA K3DU4 : " 
 
   read q 
 
   Bagi=$(echo "$p /$q" | bc) 
 
   echo "dan hasilnya Adalah = $Bagi" 
 
   sleep 5 
 
   } 
 
 
 
   MENU=1 
 
 
 
   while [ $MENU ] 
 
   do 
 
   clear 

   echo "=========================================="

   echo "  BISMILLAHIR RAHMANIR RAHIIM "
   echo "    KALKULATOR M404 : )     " 
   echo "  Jangan lupa suscribe my Channel "
   echo "       @m404new "

   echo "------------------------------------------" 
 
   echo "1 . Penambahan" 
 
   echo "2 . Pengurangan" 
 
   echo "3 . Perkalian" 
 
   echo "4 . Pembagian" 
 
   echo "5 . Exit" 
 
   echo "Pilihan Menu : " 
 
   read MENU 
 
   case $MENU in 
 
   1) penambahan 
 
   ;; 
 
   2) pengurangan 
 
   ;; 
 
   3) perkalian 
 
   ;; 
 
   4) pembagian 
 
   ;; 
 
   5) echo "Terima Kasih telah memakai jasa saya :)" 
 
   exit 
 
   ;; 
 
   *) echo "SALAH YOU BOSS" 
 
   sleep 3 
 
   esac 
 
   done
